- fixed build conflict with llh.
  /usr/include/sys/types.h:88: error: two or more data types
                                      in declaration specifiers

  types.h:88

  #ifndef __off_t_defined
  # ifndef __USE_FILE_OFFSET64
  typedef __off_t off_t;
  # else
  typedef __off64_t off_t;
  # endif
  # define __off_t_defined
  #endif

Changed files:
    lynx-autoconf.patch -> 1.8